name: Docs
on: [workflow_dispatch]
# on: [push, pull_request, workflow_dispatch]
# on:
#   schedule:
#     - cron: '0 0 * * 0'
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      # - name: Install fande dependencies
      #   run: |
      #     pip install gpytorch pytorch-lightning
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme rst2pdf
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true      
      - name: Generate pdf
        run: sphinx-build -b pdf docs/source _build
